# Generated by Django 2.2.6 on 2019-11-16 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsolaInstance',
        ),
    ]
