# Generated by Django 2.2.6 on 2019-11-16 22:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_delete_consolainstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_desc', models.CharField(help_text='Ingrese Descripcion de la conectividad', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CS',
            fields=[
                ('cs_id', models.CharField(help_text='Ingrese ID de la Consola', max_length=10, primary_key='True', serialize=False)),
                ('cs_nom', models.CharField(help_text='Ingrese Nombre de la Consola', max_length=100)),
                ('cs_price', models.IntegerField(help_text='Ingrese el precio de la consola (Ej: $ 999 999).')),
                ('cs_wght', models.IntegerField(help_text='Ingrese el peso de la consola en gramos.')),
                ('cs_descr', models.TextField(help_text='Ingrese la descripcion de la consola.', max_length=3000)),
                ('cs_res', models.CharField(help_text='Ingrese resoluciones soportadas', max_length=50)),
                ('cs_color', models.CharField(help_text='Ingrese color(es).', max_length=50)),
                ('cs_storage', models.CharField(help_text='Ingrese almacenamiento.', max_length=50)),
                ('cs_main_img', models.ImageField(null=True, upload_to='gallery')),
                ('cs_conn', models.ManyToManyField(to='console.Conn')),
            ],
        ),
        migrations.CreateModel(
            name='CSInstance',
            fields=[
                ('cinst_id', models.UUIDField(default=uuid.uuid4, help_text='ID para esta unidad', primary_key=True, serialize=False)),
                ('cinst_on_stock', models.BooleanField(null=True)),
                ('cinst_cs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.CS')),
            ],
            options={
                'ordering': ['cinst_id'],
            },
        ),
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_nom', models.CharField(help_text='Ingrese Nombre de la plataforma', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='consola',
            name='con_conectividad',
        ),
        migrations.RemoveField(
            model_name='consola',
            name='con_tipo',
        ),
        migrations.DeleteModel(
            name='Conectividad',
        ),
        migrations.DeleteModel(
            name='Consola',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.AddField(
            model_name='cs',
            name='cs_plat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='console.Plat'),
        ),
    ]
