# Generated by Django 2.2.6 on 2019-11-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.CharField(help_text='Ingrese el id de la region', max_length=5, primary_key='True', serialize=False)),
                ('reg_nombre', models.CharField(help_text='Ingrese nombre de la región', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuent_rut', models.CharField(help_text='Ingrese rut Ej: 12345678-9', max_length=9, primary_key='True', serialize=False)),
                ('cuent_email', models.EmailField(help_text='Ingrese email EJ: hola@gmail.com', max_length=30)),
                ('cuent_pass', models.CharField(help_text='Ingrese contraseña', max_length=30)),
                ('cuent_nombre', models.CharField(help_text='Ingrese su nombre', max_length=50)),
                ('cuent_ape', models.CharField(default=None, help_text='Ingrese su apellido', max_length=50)),
                ('cuent_fecnac', models.DateField(default=None)),
                ('desp_telef', models.CharField(default=None, help_text='Ingrese su número de teléfono', max_length=10)),
                ('com_nombre', models.CharField(default=None, help_text='Ingrese el nombre de su comuna', max_length=10)),
                ('desp_direccion', models.TextField(default=None, help_text='Ingrese su dirección', max_length=100)),
                ('desp_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Region')),
            ],
        ),
    ]
