# Generated by Django 2.2.6 on 2019-11-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_vg_vg_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='vg',
            name='vg_img2',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='vg',
            name='vg_img3',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
