# Generated by Django 2.2.6 on 2019-11-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20191104_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='vg',
            name='vg_img4',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
