# Generated by Django 2.2.6 on 2019-11-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_vg_vg_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vg',
            name='vg_descr',
            field=models.TextField(help_text='Ingrese la descripcion del juego.', max_length=3000),
        ),
    ]
