# Generated by Django 2.2.6 on 2019-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20191104_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vg',
            name='vg_local_plyr',
            field=models.IntegerField(help_text='Ingrese La cantidad de jugadores local (Ej: 1).'),
        ),
        migrations.AlterField(
            model_name='vg',
            name='vg_online_plyr',
            field=models.IntegerField(help_text='Ingrese La cantidad de jugadores online.'),
        ),
    ]
