# Generated by Django 2.2.6 on 2019-12-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20191107_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('ban_id', models.CharField(help_text='Ingrese ID del Banner', max_length=10, primary_key='True', serialize=False)),
                ('ban_game1', models.CharField(help_text='Ingrese Nombre del Juego', max_length=100)),
                ('ban_img1', models.ImageField(null=True, upload_to='gallery')),
                ('ban_game2', models.CharField(help_text='Ingrese Nombre del Juego', max_length=100)),
                ('ban_img2', models.ImageField(null=True, upload_to='gallery')),
                ('ban_game3', models.CharField(help_text='Ingrese Nombre del Juego', max_length=100)),
                ('ban_img3', models.ImageField(null=True, upload_to='gallery')),
            ],
        ),
    ]
