# Generated by Django 2.2.6 on 2019-12-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='ban_game1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ban_game2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ban_game3',
        ),
        migrations.AddField(
            model_name='banner',
            name='ban_vg',
            field=models.ManyToManyField(to='game.VG'),
        ),
    ]
