# Generated by Django 2.2.6 on 2019-12-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20191205_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='ban_img1',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ban_img2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='ban_img3',
        ),
        migrations.AddField(
            model_name='vg',
            name='vg_banner',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
